### ISSUE TITLE
Editable controls the ability to resize columns and tables

### ISSUE THREAD

**Issue by tommerty** [TypeCellOS/BlockNote#1244]
**Is your feature request related to a problem? Please describe.**
When editable is false, it would be great to have an option/prop to decide should blocks that can be resized like tables and columns the ability to do so. I've not found a meaningful way to control this, and as someone who's using this as a "blog writer" the ability to modify the width is a little strange for end users.

**Describe the solution you'd like**
When editable is false, users shouldn't be able to resize.

**Describe alternatives you've considered**
I've made attempts with some CSS that does hide the resize on columns, but if the user happens to click and drag in the right place they can still grab it.

Example CSS:
```css
.bn-container[data-theming-readonly="true"] [data-node-type="column"] {
    box-shadow: none !important; /* Remove resize indicator */
    cursor: default !important; /* Remove resize cursor */
}
```

**Additional context**
There is likely a way to do this, but it's not outlined in documentation, hasn't been shared in the GitHub/Discord, or I'm just terrible at searching. I'm still learning the innards of Blocknote and a solution is potentially obvious to most..

**Bonus**
[ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖
