### ISSUE TITLE
Trying to insert the cursor at the end of the element inserts the cursor at the start

### ISSUE THREAD

**Issue by juliomuhlbauer** [TypeCellOS/BlockNote#1523]
The Alert component does work perfectly because of its flex-grow: 1.
I managed to fix it with this css style:
```css
.bn-block-content > * {
    width: 100%;
  }
```

https://github.com/user-attachments/assets/0fca76f0-d264-4083-9404-22f8dd9c1a82
