### ISSUE TITLE
Scroll appears in table when content becomes too long

### ISSUE THREAD

**Issue by maieutiquer** [TypeCellOS/BlockNote#1737]
**Describe the bug**
Scroll appears in table when content becomes too long and pushes the table to be as wide as the editor

**To Reproduce**
<clear steps to reproduce are super helpful! Best is to provide an online sandbox, [click to create one](https://stackblitz.com/github/TypeCellOS/BlockNote/tree/main/examples/01-basic/01-minimal?file=App.tsx)>

1. Open homepage playground or stackblitz sandbox
2. Create a new empty table
3. Type (or paste) some very long text in one of the cells until it makes the table at least as wide as the editor and the text overflows on a second line inside its cell

<img width="630" alt="Image" src="https://github.com/user-attachments/assets/e0104665-53b6-4b55-a93f-bf1240967df1" />

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/727cf0e1-2151-4905-9676-0d6cf1088440" />

This is also broken the same way in our application that uses Blocknote.

**Misc**

- Node version:
- Package manager:
- Browser: Chrome latest
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Agree, this is a UX bug as the table becomes just a little too wide

**Comment by maieutiquer** [comment]
We worked around it on our side like this:
```css
.bn-container .bn-editor [data-content-type='table'] .tableWrapper-inner {
  /* 22px is the width of the table resize handle - width 18px + padding 4px */
  padding-right: 22px;
}
```
