### ISSUE TITLE
Incorrect blocknote styles affecting Mantine ToolTip component styles

### ISSUE THREAD

**Issue by mag1yar** [TypeCellOS/BlockNote#566]
**Describe the bug**
I have identified an issue when using the **Mantine** and **BlockNote** libraries in my project. In the blocknote [styles](https://github.com/TypeCellOS/BlockNote/blob/main/packages/react/src/editor/styles.css) **210** line, the **.bn-container** selector is missing, causing a conflict with the **Mantine ToolTip** component styles.

**To Reproduce**
1. Add blocknote and Mantine styles to the project.
2. Use the Mantine ToolTip component.

**Expected behavior**
```css
.bn-container .mantine-Tooltip-tooltip {
    background-color: transparent;
    border: none;
    border-radius: 0;
    box-shadow: none;
    padding: 0;
}
```
**Actual behavior**
```css
.mantine-Tooltip-tooltip {
    background-color: transparent;
    border: none;
    border-radius: 0;
    box-shadow: none;
    padding: 0;
}
```

**Misc**
- Nextjs: 14.1.0
- Mantine: 7.5.1
- BlockNote: 0.11.2
- Package manager: yarn@4.0.1
- Browser: Microsoft Edge
